version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis

  backend:
    image: backend
    build:
      dockerfile: Dockerfile.backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    container_name: backend
    depends_on: 
      - db
      - redis
  
  frontend:
    image: frontend
    build:
      dockerfile: Dockerfile.frontend
    container_name: frontend
    depends_on: 
      - backend
  
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    container_name: nginx
    depends_on:
      - backend
      - frontend

