version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    container_name: redis

  backend:
    image: backend
    build:
      dockerfile: Dockerfile.backend
    ports:
     - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    container_name: backend
    depends_on: 
      - db
      - redis
  
  frontend:
    image: frontend
    ports:
     - 5000:5000
    build:
      dockerfile: Dockerfile.frontend
    container_name: frontend
    depends_on: 
      - backend
