version: '3.8'

services:
  redis:
    image: redis
    container_name: redis

  backend:
    image: backend
    build:
      dockerfile: Dockerfile.backend
    ports:
     - 8080:8080
    environment:
      - REDIS_HOST=redis
    container_name: backend
  
  frontend:
    image: frontend
    ports:
     - 5000:5000
    build:
      dockerfile: Dockerfile.frontend
    container_name: frontend
